# Generated by Django 4.2 on 2023-04-29 15:55

import csv
import os

from django.db import migrations
from django.conf import settings

from mango.models import MangoProduct


def create_mango_products(apps, schema_editor):
    with open(
        os.path.join(
            settings.MEDIA_ROOT, "mango_data", "mango_products", "mango_products.csv"
        )
    ) as csvfile:
        reader = csv.DictReader(csvfile)
        for row in reader:
            MangoProduct.objects.create(
                id=row["mango_product_id"], name=row["product_name"]
            )


class Migration(migrations.Migration):

    dependencies = [
        ("mango", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_mango_products)]
