# Generated by Django 4.2 on 2023-04-29 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mango", "0002_auto_20230429_1555"),
    ]

    operations = [
        migrations.RenameField(
            model_name="mangoproductfile",
            old_name="mango_product_id",
            new_name="mango_product",
        ),
    ]
