# Generated by Django 4.2 on 2023-04-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mango", "0003_rename_mango_product_id_mangoproductfile_mango_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="mangoproductfile",
            name="is_processed",
            field=models.BooleanField(default=False),
        ),
    ]
