# Generated by Django 4.2 on 2023-04-30 17:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("mango", "0005_remove_mangoproductfile_is_processed_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MangoProductAnnotations",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("create_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "field_label",
                    models.CharField(
                        choices=[
                            ("metric_name", "metric_name"),
                            ("slice_name", "slice_name"),
                        ],
                        max_length=128,
                    ),
                ),
                ("field_value", models.CharField(max_length=1024)),
                (
                    "calculation_type",
                    models.CharField(choices=[("point", "point")], max_length=128),
                ),
                (
                    "mango_product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mango.mangoproduct",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
