# Generated by Django 4.2 on 2023-04-30 17:08
import csv
import os

from django.conf import settings
from django.db import migrations

from mango.models import MangoProduct, MangoProductAnnotation


def create_mango_annotations(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("mango", "0007_rename_mangoproductannotations_mangoproductannotation"),
    ]

    operations = [migrations.RunPython(create_mango_annotations)]
