# Generated by Django 4.2 on 2023-05-02 00:27
from mango.utils import create_mango_annotations

from django.db import migrations


def annotate(apps, schema_editor):
    create_mango_annotations("us_food_delivery_annotations.csv")


class Migration(migrations.Migration):

    dependencies = [
        ("mango", "0008_auto_20230430_1708"),
    ]

    operations = [migrations.RunPython(annotate)]
