# Generated by Django 4.2 on 2023-05-05 17:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("mango", "0010_mangoproduct_report_product_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MangoAnnotationSourceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("create_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("source_file", models.FileField(upload_to="mango_data/mango_metrics")),
                (
                    "mango_product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mango.mangoproduct",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="MangoProductSourceFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("create_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "model_key",
                    models.CharField(
                        choices=[
                            ("YipitReportCampaign", "YipitReportCampaign"),
                            ("MangoProduct", "MangoProduct"),
                        ],
                        max_length=128,
                    ),
                ),
                (
                    "source_file",
                    models.FileField(upload_to="mango_data/mango_products"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="YipitReportCampaignDataFile",
            fields=[
                ("create_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("product_id", models.UUIDField()),
                ("report_url", models.URLField()),
                ("campaign_id", models.UUIDField()),
                ("sent_date", models.DateTimeField()),
                ("subject_line", models.CharField(max_length=256)),
                (
                    "mango_product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mango.mangoproduct",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="YipitReportCampaign",
        ),
    ]
