# Generated by Django 4.2 on 2023-05-05 18:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mango", "0012_alter_mangoproductsourcefile_model_key"),
    ]

    operations = [
        migrations.RenameField(
            model_name="yipitreportcampaigndatafile",
            old_name="mango_product_id",
            new_name="mango_product",
        ),
    ]
