# Generated by Django 4.2 on 2023-04-30 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_backend", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractedpitdata",
            name="date",
            field=models.CharField(max_length=32),
        ),
    ]
