# Generated by Django 4.2 on 2023-04-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_backend", "0003_rename_date_extractedpitdata_raw_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedpitdata",
            name="annotated",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
