# Generated by Django 4.2 on 2023-04-30 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_backend", "0004_extractedpitdata_annotated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractedpitdata",
            name="annotated",
            field=models.BooleanField(default=False),
        ),
    ]
