# Generated by Django 4.2 on 2023-04-30 17:48

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("mango", "0008_auto_20230430_1708"),
        ("parser_backend", "0005_alter_extractedpitdata_annotated"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessedPitData",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("create_datetime", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                (
                    "metric_field",
                    models.CharField(
                        choices=[
                            ("raw_analysis_name", "raw_analysis_name"),
                            ("slice_value", "slice_value"),
                            ("section_header_1", "section_header_1"),
                            ("section_header_2", "section_header_2"),
                        ],
                        max_length=32,
                    ),
                ),
                ("metric_label", models.CharField(max_length=1024)),
                ("value_scaler", models.DecimalField(decimal_places=2, max_digits=20)),
                (
                    "slice_field",
                    models.CharField(
                        choices=[
                            ("raw_analysis_name", "raw_analysis_name"),
                            ("slice_value", "slice_value"),
                            ("section_header_1", "section_header_1"),
                            ("section_header_2", "section_header_2"),
                        ],
                        max_length=32,
                    ),
                ),
                ("slice_label", models.CharField(max_length=1024)),
                (
                    "periodicity",
                    models.CharField(
                        choices=[
                            ("daily", "daily"),
                            ("week", "week"),
                            ("month", "month"),
                            ("quarter", "quarter"),
                            ("year", "year"),
                        ],
                        max_length=32,
                    ),
                ),
                ("period_end_time_delta", models.SmallIntegerField()),
                ("dates_start_period", models.BooleanField(default=False)),
                ("timeseries_id", models.UUIDField()),
                (
                    "mango_product_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="mango.mangoproductfile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
