# Generated by Django 4.2 on 2023-04-30 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_backend", "0006_processedpitdata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractedpitdata",
            name="annotated",
            field=models.IntegerField(
                choices=[(1, "Unannotated"), (2, "Skipped"), (3, "Annotated")],
                default=1,
            ),
        ),
    ]
