# Generated by Django 4.2 on 2023-04-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_backend", "0007_alter_extractedpitdata_annotated"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processedpitdata",
            name="timeseries_id",
            field=models.UUIDField(unique=True),
        ),
    ]
