# Generated by Django 4.2 on 2023-05-01 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("parser_backend", "0008_alter_processedpitdata_timeseries_id"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processedpitdata",
            name="period_end_time_delta",
        ),
    ]
