# Generated by Django 4.2 on 2023-05-01 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_backend", "0009_remove_processedpitdata_period_end_time_delta"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extractedpitdata",
            name="slice_value",
            field=models.CharField(max_length=1024, null=True),
        ),
    ]
