# Generated by Django 4.2 on 2023-05-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("parser_backend", "0010_alter_extractedpitdata_slice_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="extractedpitdata",
            name="publication_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
